### ISSUE TITLE
win系统除了虚拟机没办法编译了吗

### ISSUE THREAD

**Issue by soberkingomi** [Bill-Haku/iLegym#1]
如题，win系统除了装黑苹果或者开虚拟机就没办法了吗

**Comment by Bill-Haku** [comment]
是的。也许还会有一些奇技淫巧可以编译但是复杂程度肯定远大于装一个虚拟机。

**Comment by soberkingomi** [comment]
> 是的。也许还会有一些奇技淫巧可以编译但是复杂程度肯定远大于装一个虚拟机。

那我还是开虚拟机吧，谢了大佬
